// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

public interface CommitReplayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.CommitReplayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * commit_request_id to identify commit responses.
   * </pre>
   *
   * <code>string commit_request_id = 1;</code>
   * @return The commitRequestId.
   */
  java.lang.String getCommitRequestId();
  /**
   * <pre>
   * commit_request_id to identify commit responses.
   * </pre>
   *
   * <code>string commit_request_id = 1;</code>
   * @return The bytes for commitRequestId.
   */
  com.google.protobuf.ByteString
      getCommitRequestIdBytes();

  /**
   * <pre>
   * replayId that may have been committed
   * </pre>
   *
   * <code>bytes replay_id = 2;</code>
   * @return The replayId.
   */
  com.google.protobuf.ByteString getReplayId();

  /**
   * <pre>
   * for failed commits
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * for failed commits
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 3;</code>
   * @return The error.
   */
  com.salesforce.eventbus.protobuf.Error getError();
  /**
   * <pre>
   * for failed commits
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 3;</code>
   */
  com.salesforce.eventbus.protobuf.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * time when server received request in epoch ms
   * </pre>
   *
   * <code>int64 process_time = 4;</code>
   * @return The processTime.
   */
  long getProcessTime();
}
