// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

public interface CommitReplayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.CommitReplayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * commit_request_id to identify commit responses
   * </pre>
   *
   * <code>string commit_request_id = 1;</code>
   * @return The commitRequestId.
   */
  java.lang.String getCommitRequestId();
  /**
   * <pre>
   * commit_request_id to identify commit responses
   * </pre>
   *
   * <code>string commit_request_id = 1;</code>
   * @return The bytes for commitRequestId.
   */
  com.google.protobuf.ByteString
      getCommitRequestIdBytes();

  /**
   * <pre>
   * replayId to commit
   * </pre>
   *
   * <code>bytes replay_id = 2;</code>
   * @return The replayId.
   */
  com.google.protobuf.ByteString getReplayId();
}
