// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

/**
 * <pre>
 *
 * Event publish result that the Publish RPC method returns. The result contains replay_id or a publish error.
 * </pre>
 *
 * Protobuf type {@code eventbus.v1.PublishResult}
 */
public final class PublishResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:eventbus.v1.PublishResult)
    PublishResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      PublishResult.class.getName());
  }
  // Use PublishResult.newBuilder() to construct.
  private PublishResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublishResult() {
    replayId_ = com.google.protobuf.ByteString.EMPTY;
    correlationKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.salesforce.eventbus.protobuf.PubSubProto.internal_static_eventbus_v1_PublishResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.salesforce.eventbus.protobuf.PubSubProto.internal_static_eventbus_v1_PublishResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.salesforce.eventbus.protobuf.PublishResult.class, com.salesforce.eventbus.protobuf.PublishResult.Builder.class);
  }

  private int bitField0_;
  public static final int REPLAY_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString replayId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Replay ID of the event
   * </pre>
   *
   * <code>bytes replay_id = 1;</code>
   * @return The replayId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getReplayId() {
    return replayId_;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private com.salesforce.eventbus.protobuf.Error error_;
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.salesforce.eventbus.protobuf.Error getError() {
    return error_ == null ? com.salesforce.eventbus.protobuf.Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   */
  @java.lang.Override
  public com.salesforce.eventbus.protobuf.ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.salesforce.eventbus.protobuf.Error.getDefaultInstance() : error_;
  }

  public static final int CORRELATION_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationKey_ = "";
  /**
   * <pre>
   * Correlation key of the ProducerEvent
   * </pre>
   *
   * <code>string correlation_key = 3;</code>
   * @return The correlationKey.
   */
  @java.lang.Override
  public java.lang.String getCorrelationKey() {
    java.lang.Object ref = correlationKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Correlation key of the ProducerEvent
   * </pre>
   *
   * <code>string correlation_key = 3;</code>
   * @return The bytes for correlationKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationKeyBytes() {
    java.lang.Object ref = correlationKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!replayId_.isEmpty()) {
      output.writeBytes(1, replayId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getError());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(correlationKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, correlationKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!replayId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, replayId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(correlationKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, correlationKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.salesforce.eventbus.protobuf.PublishResult)) {
      return super.equals(obj);
    }
    com.salesforce.eventbus.protobuf.PublishResult other = (com.salesforce.eventbus.protobuf.PublishResult) obj;

    if (!getReplayId()
        .equals(other.getReplayId())) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getCorrelationKey()
        .equals(other.getCorrelationKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPLAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReplayId().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (37 * hash) + CORRELATION_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.salesforce.eventbus.protobuf.PublishResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.salesforce.eventbus.protobuf.PublishResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.salesforce.eventbus.protobuf.PublishResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.salesforce.eventbus.protobuf.PublishResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   * Event publish result that the Publish RPC method returns. The result contains replay_id or a publish error.
   * </pre>
   *
   * Protobuf type {@code eventbus.v1.PublishResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eventbus.v1.PublishResult)
      com.salesforce.eventbus.protobuf.PublishResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.salesforce.eventbus.protobuf.PubSubProto.internal_static_eventbus_v1_PublishResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.salesforce.eventbus.protobuf.PubSubProto.internal_static_eventbus_v1_PublishResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.salesforce.eventbus.protobuf.PublishResult.class, com.salesforce.eventbus.protobuf.PublishResult.Builder.class);
    }

    // Construct using com.salesforce.eventbus.protobuf.PublishResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      replayId_ = com.google.protobuf.ByteString.EMPTY;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      correlationKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.salesforce.eventbus.protobuf.PubSubProto.internal_static_eventbus_v1_PublishResult_descriptor;
    }

    @java.lang.Override
    public com.salesforce.eventbus.protobuf.PublishResult getDefaultInstanceForType() {
      return com.salesforce.eventbus.protobuf.PublishResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.salesforce.eventbus.protobuf.PublishResult build() {
      com.salesforce.eventbus.protobuf.PublishResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.salesforce.eventbus.protobuf.PublishResult buildPartial() {
      com.salesforce.eventbus.protobuf.PublishResult result = new com.salesforce.eventbus.protobuf.PublishResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.salesforce.eventbus.protobuf.PublishResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.replayId_ = replayId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.correlationKey_ = correlationKey_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.salesforce.eventbus.protobuf.PublishResult) {
        return mergeFrom((com.salesforce.eventbus.protobuf.PublishResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.salesforce.eventbus.protobuf.PublishResult other) {
      if (other == com.salesforce.eventbus.protobuf.PublishResult.getDefaultInstance()) return this;
      if (other.getReplayId() != com.google.protobuf.ByteString.EMPTY) {
        setReplayId(other.getReplayId());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (!other.getCorrelationKey().isEmpty()) {
        correlationKey_ = other.correlationKey_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              replayId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              correlationKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString replayId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Replay ID of the event
     * </pre>
     *
     * <code>bytes replay_id = 1;</code>
     * @return The replayId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getReplayId() {
      return replayId_;
    }
    /**
     * <pre>
     * Replay ID of the event
     * </pre>
     *
     * <code>bytes replay_id = 1;</code>
     * @param value The replayId to set.
     * @return This builder for chaining.
     */
    public Builder setReplayId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      replayId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Replay ID of the event
     * </pre>
     *
     * <code>bytes replay_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplayId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      replayId_ = getDefaultInstance().getReplayId();
      onChanged();
      return this;
    }

    private com.salesforce.eventbus.protobuf.Error error_;
    private com.google.protobuf.SingleFieldBuilder<
        com.salesforce.eventbus.protobuf.Error, com.salesforce.eventbus.protobuf.Error.Builder, com.salesforce.eventbus.protobuf.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     * @return The error.
     */
    public com.salesforce.eventbus.protobuf.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.salesforce.eventbus.protobuf.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder setError(com.salesforce.eventbus.protobuf.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder setError(
        com.salesforce.eventbus.protobuf.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder mergeError(com.salesforce.eventbus.protobuf.Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          error_ != null &&
          error_ != com.salesforce.eventbus.protobuf.Error.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000002);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public com.salesforce.eventbus.protobuf.Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public com.salesforce.eventbus.protobuf.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.salesforce.eventbus.protobuf.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.salesforce.eventbus.protobuf.Error, com.salesforce.eventbus.protobuf.Error.Builder, com.salesforce.eventbus.protobuf.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.salesforce.eventbus.protobuf.Error, com.salesforce.eventbus.protobuf.Error.Builder, com.salesforce.eventbus.protobuf.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.lang.Object correlationKey_ = "";
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @return The correlationKey.
     */
    public java.lang.String getCorrelationKey() {
      java.lang.Object ref = correlationKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @return The bytes for correlationKey.
     */
    public com.google.protobuf.ByteString
        getCorrelationKeyBytes() {
      java.lang.Object ref = correlationKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @param value The correlationKey to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationKey() {
      correlationKey_ = getDefaultInstance().getCorrelationKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @param value The bytes for correlationKey to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:eventbus.v1.PublishResult)
  }

  // @@protoc_insertion_point(class_scope:eventbus.v1.PublishResult)
  private static final com.salesforce.eventbus.protobuf.PublishResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.salesforce.eventbus.protobuf.PublishResult();
  }

  public static com.salesforce.eventbus.protobuf.PublishResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishResult>
      PARSER = new com.google.protobuf.AbstractParser<PublishResult>() {
    @java.lang.Override
    public PublishResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublishResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublishResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.salesforce.eventbus.protobuf.PublishResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

