// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

public interface PublishResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.PublishResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Replay ID of the event
   * </pre>
   *
   * <code>bytes replay_id = 1;</code>
   * @return The replayId.
   */
  com.google.protobuf.ByteString getReplayId();

  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   * @return The error.
   */
  com.salesforce.eventbus.protobuf.Error getError();
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   */
  com.salesforce.eventbus.protobuf.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * Correlation key of the ProducerEvent
   * </pre>
   *
   * <code>string correlation_key = 3;</code>
   * @return The correlationKey.
   */
  java.lang.String getCorrelationKey();
  /**
   * <pre>
   * Correlation key of the ProducerEvent
   * </pre>
   *
   * <code>string correlation_key = 3;</code>
   * @return The bytes for correlationKey.
   */
  com.google.protobuf.ByteString
      getCorrelationKeyBytes();
}
