// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

public interface PublishRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.PublishRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Topic to publish on
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The topicName.
   */
  java.lang.String getTopicName();
  /**
   * <pre>
   * Topic to publish on
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The bytes for topicName.
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  java.util.List<com.salesforce.eventbus.protobuf.ProducerEvent> 
      getEventsList();
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  com.salesforce.eventbus.protobuf.ProducerEvent getEvents(int index);
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  int getEventsCount();
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  java.util.List<? extends com.salesforce.eventbus.protobuf.ProducerEventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  com.salesforce.eventbus.protobuf.ProducerEventOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <pre>
   * For internal Salesforce use only.
   * </pre>
   *
   * <code>string auth_refresh = 3;</code>
   * @return The authRefresh.
   */
  java.lang.String getAuthRefresh();
  /**
   * <pre>
   * For internal Salesforce use only.
   * </pre>
   *
   * <code>string auth_refresh = 3;</code>
   * @return The bytes for authRefresh.
   */
  com.google.protobuf.ByteString
      getAuthRefreshBytes();
}
