// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

public final class PubSubProto {
  private PubSubProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      PubSubProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_TopicInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_TopicInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_TopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_TopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_EventHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_EventHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ProducerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_ProducerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ConsumerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_ConsumerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_PublishResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_PublishResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_SchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_SchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_SchemaInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_SchemaInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_PublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_PublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_PublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_PublishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ManagedFetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_ManagedFetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ManagedFetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_ManagedFetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_CommitReplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_CommitReplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_CommitReplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventbus_v1_CommitReplayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pubsub_api.proto\022\013eventbus.v1\"\203\001\n\tTopi" +
      "cInfo\022\022\n\ntopic_name\030\001 \001(\t\022\023\n\013tenant_guid" +
      "\030\002 \001(\t\022\023\n\013can_publish\030\003 \001(\010\022\025\n\rcan_subsc" +
      "ribe\030\004 \001(\010\022\021\n\tschema_id\030\005 \001(\t\022\016\n\006rpc_id\030" +
      "\006 \001(\t\"\"\n\014TopicRequest\022\022\n\ntopic_name\030\001 \001(" +
      "\t\")\n\013EventHeader\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\014\"j\n\rProducerEvent\022\n\n\002id\030\001 \001(\t\022\021\n\tsch" +
      "ema_id\030\002 \001(\t\022\017\n\007payload\030\003 \001(\014\022)\n\007headers" +
      "\030\004 \003(\0132\030.eventbus.v1.EventHeader\"M\n\rCons" +
      "umerEvent\022)\n\005event\030\001 \001(\0132\032.eventbus.v1.P" +
      "roducerEvent\022\021\n\treplay_id\030\002 \001(\014\"^\n\rPubli" +
      "shResult\022\021\n\treplay_id\030\001 \001(\014\022!\n\005error\030\002 \001" +
      "(\0132\022.eventbus.v1.Error\022\027\n\017correlation_ke" +
      "y\030\003 \001(\t\":\n\005Error\022$\n\004code\030\001 \001(\0162\026.eventbu" +
      "s.v1.ErrorCode\022\013\n\003msg\030\002 \001(\t\"\224\001\n\014FetchReq" +
      "uest\022\022\n\ntopic_name\030\001 \001(\t\0220\n\rreplay_prese" +
      "t\030\002 \001(\0162\031.eventbus.v1.ReplayPreset\022\021\n\tre" +
      "play_id\030\003 \001(\014\022\025\n\rnum_requested\030\004 \001(\005\022\024\n\014" +
      "auth_refresh\030\005 \001(\t\"\204\001\n\rFetchResponse\022*\n\006" +
      "events\030\001 \003(\0132\032.eventbus.v1.ConsumerEvent" +
      "\022\030\n\020latest_replay_id\030\002 \001(\014\022\016\n\006rpc_id\030\003 \001" +
      "(\t\022\035\n\025pending_num_requested\030\004 \001(\005\"\"\n\rSch" +
      "emaRequest\022\021\n\tschema_id\030\001 \001(\t\"D\n\nSchemaI" +
      "nfo\022\023\n\013schema_json\030\001 \001(\t\022\021\n\tschema_id\030\002 " +
      "\001(\t\022\016\n\006rpc_id\030\003 \001(\t\"f\n\016PublishRequest\022\022\n" +
      "\ntopic_name\030\001 \001(\t\022*\n\006events\030\002 \003(\0132\032.even" +
      "tbus.v1.ProducerEvent\022\024\n\014auth_refresh\030\003 " +
      "\001(\t\"a\n\017PublishResponse\022+\n\007results\030\001 \003(\0132" +
      "\032.eventbus.v1.PublishResult\022\021\n\tschema_id" +
      "\030\002 \001(\t\022\016\n\006rpc_id\030\003 \001(\t\"\267\001\n\023ManagedFetchR" +
      "equest\022\027\n\017subscription_id\030\001 \001(\t\022\026\n\016devel" +
      "oper_name\030\002 \001(\t\022\025\n\rnum_requested\030\003 \001(\005\022\024" +
      "\n\014auth_refresh\030\004 \001(\t\022B\n\030commit_replay_id" +
      "_request\030\005 \001(\0132 .eventbus.v1.CommitRepla" +
      "yRequest\"\307\001\n\024ManagedFetchResponse\022*\n\006eve" +
      "nts\030\001 \003(\0132\032.eventbus.v1.ConsumerEvent\022\030\n" +
      "\020latest_replay_id\030\002 \001(\014\022\016\n\006rpc_id\030\003 \001(\t\022" +
      "\035\n\025pending_num_requested\030\004 \001(\005\022:\n\017commit" +
      "_response\030\005 \001(\0132!.eventbus.v1.CommitRepl" +
      "ayResponse\"C\n\023CommitReplayRequest\022\031\n\021com" +
      "mit_request_id\030\001 \001(\t\022\021\n\treplay_id\030\002 \001(\014\"" +
      "}\n\024CommitReplayResponse\022\031\n\021commit_reques" +
      "t_id\030\001 \001(\t\022\021\n\treplay_id\030\002 \001(\014\022!\n\005error\030\003" +
      " \001(\0132\022.eventbus.v1.Error\022\024\n\014process_time" +
      "\030\004 \001(\003*1\n\tErrorCode\022\013\n\007UNKNOWN\020\000\022\013\n\007PUBL" +
      "ISH\020\001\022\n\n\006COMMIT\020\002*4\n\014ReplayPreset\022\n\n\006LAT" +
      "EST\020\000\022\014\n\010EARLIEST\020\001\022\n\n\006CUSTOM\020\0022\304\003\n\006PubS" +
      "ub\022F\n\tSubscribe\022\031.eventbus.v1.FetchReque" +
      "st\032\032.eventbus.v1.FetchResponse(\0010\001\022@\n\tGe" +
      "tSchema\022\032.eventbus.v1.SchemaRequest\032\027.ev" +
      "entbus.v1.SchemaInfo\022=\n\010GetTopic\022\031.event" +
      "bus.v1.TopicRequest\032\026.eventbus.v1.TopicI" +
      "nfo\022D\n\007Publish\022\033.eventbus.v1.PublishRequ" +
      "est\032\034.eventbus.v1.PublishResponse\022N\n\rPub" +
      "lishStream\022\033.eventbus.v1.PublishRequest\032" +
      "\034.eventbus.v1.PublishResponse(\0010\001\022[\n\020Man" +
      "agedSubscribe\022 .eventbus.v1.ManagedFetch" +
      "Request\032!.eventbus.v1.ManagedFetchRespon" +
      "se(\0010\001Ba\n com.salesforce.eventbus.protob" +
      "ufB\013PubSubProtoP\001Z.github.com/developerf" +
      "orce/pub-sub-api/go/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_eventbus_v1_TopicInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventbus_v1_TopicInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_TopicInfo_descriptor,
        new java.lang.String[] { "TopicName", "TenantGuid", "CanPublish", "CanSubscribe", "SchemaId", "RpcId", });
    internal_static_eventbus_v1_TopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eventbus_v1_TopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_TopicRequest_descriptor,
        new java.lang.String[] { "TopicName", });
    internal_static_eventbus_v1_EventHeader_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_eventbus_v1_EventHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_EventHeader_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_eventbus_v1_ProducerEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_eventbus_v1_ProducerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_ProducerEvent_descriptor,
        new java.lang.String[] { "Id", "SchemaId", "Payload", "Headers", });
    internal_static_eventbus_v1_ConsumerEvent_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_eventbus_v1_ConsumerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_ConsumerEvent_descriptor,
        new java.lang.String[] { "Event", "ReplayId", });
    internal_static_eventbus_v1_PublishResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_eventbus_v1_PublishResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_PublishResult_descriptor,
        new java.lang.String[] { "ReplayId", "Error", "CorrelationKey", });
    internal_static_eventbus_v1_Error_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_eventbus_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_Error_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_eventbus_v1_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_eventbus_v1_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_FetchRequest_descriptor,
        new java.lang.String[] { "TopicName", "ReplayPreset", "ReplayId", "NumRequested", "AuthRefresh", });
    internal_static_eventbus_v1_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_eventbus_v1_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_FetchResponse_descriptor,
        new java.lang.String[] { "Events", "LatestReplayId", "RpcId", "PendingNumRequested", });
    internal_static_eventbus_v1_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_eventbus_v1_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_SchemaRequest_descriptor,
        new java.lang.String[] { "SchemaId", });
    internal_static_eventbus_v1_SchemaInfo_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_eventbus_v1_SchemaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_SchemaInfo_descriptor,
        new java.lang.String[] { "SchemaJson", "SchemaId", "RpcId", });
    internal_static_eventbus_v1_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_eventbus_v1_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_PublishRequest_descriptor,
        new java.lang.String[] { "TopicName", "Events", "AuthRefresh", });
    internal_static_eventbus_v1_PublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_eventbus_v1_PublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_PublishResponse_descriptor,
        new java.lang.String[] { "Results", "SchemaId", "RpcId", });
    internal_static_eventbus_v1_ManagedFetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_eventbus_v1_ManagedFetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_ManagedFetchRequest_descriptor,
        new java.lang.String[] { "SubscriptionId", "DeveloperName", "NumRequested", "AuthRefresh", "CommitReplayIdRequest", });
    internal_static_eventbus_v1_ManagedFetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_eventbus_v1_ManagedFetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_ManagedFetchResponse_descriptor,
        new java.lang.String[] { "Events", "LatestReplayId", "RpcId", "PendingNumRequested", "CommitResponse", });
    internal_static_eventbus_v1_CommitReplayRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_eventbus_v1_CommitReplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_CommitReplayRequest_descriptor,
        new java.lang.String[] { "CommitRequestId", "ReplayId", });
    internal_static_eventbus_v1_CommitReplayResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_eventbus_v1_CommitReplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventbus_v1_CommitReplayResponse_descriptor,
        new java.lang.String[] { "CommitRequestId", "ReplayId", "Error", "ProcessTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
