// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

/**
 * <pre>
 *
 * Supported subscription replay start values.
 * By default, the subscription will start at the tip of the stream if ReplayPreset is not specified.
 * </pre>
 *
 * Protobuf enum {@code eventbus.v1.ReplayPreset}
 */
public enum ReplayPreset
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Start the subscription at the tip of the stream.
   * </pre>
   *
   * <code>LATEST = 0;</code>
   */
  LATEST(0),
  /**
   * <pre>
   * Start the subscription at the earliest point in the stream.
   * </pre>
   *
   * <code>EARLIEST = 1;</code>
   */
  EARLIEST(1),
  /**
   * <pre>
   * Start the subscription after a custom point in the stream. This must be set with a valid replay_id in the FetchRequest.
   * </pre>
   *
   * <code>CUSTOM = 2;</code>
   */
  CUSTOM(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ReplayPreset.class.getName());
  }
  /**
   * <pre>
   * Start the subscription at the tip of the stream.
   * </pre>
   *
   * <code>LATEST = 0;</code>
   */
  public static final int LATEST_VALUE = 0;
  /**
   * <pre>
   * Start the subscription at the earliest point in the stream.
   * </pre>
   *
   * <code>EARLIEST = 1;</code>
   */
  public static final int EARLIEST_VALUE = 1;
  /**
   * <pre>
   * Start the subscription after a custom point in the stream. This must be set with a valid replay_id in the FetchRequest.
   * </pre>
   *
   * <code>CUSTOM = 2;</code>
   */
  public static final int CUSTOM_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReplayPreset valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ReplayPreset forNumber(int value) {
    switch (value) {
      case 0: return LATEST;
      case 1: return EARLIEST;
      case 2: return CUSTOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReplayPreset>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReplayPreset> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReplayPreset>() {
          public ReplayPreset findValueByNumber(int number) {
            return ReplayPreset.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.salesforce.eventbus.protobuf.PubSubProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final ReplayPreset[] VALUES = values();

  public static ReplayPreset valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReplayPreset(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:eventbus.v1.ReplayPreset)
}

