// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pubsub_api.proto
// Protobuf Java Version: 4.27.3

package com.salesforce.eventbus.protobuf;

public interface TopicInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.TopicInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Topic name
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The topicName.
   */
  java.lang.String getTopicName();
  /**
   * <pre>
   * Topic name
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The bytes for topicName.
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <pre>
   * Tenant/org GUID
   * </pre>
   *
   * <code>string tenant_guid = 2;</code>
   * @return The tenantGuid.
   */
  java.lang.String getTenantGuid();
  /**
   * <pre>
   * Tenant/org GUID
   * </pre>
   *
   * <code>string tenant_guid = 2;</code>
   * @return The bytes for tenantGuid.
   */
  com.google.protobuf.ByteString
      getTenantGuidBytes();

  /**
   * <pre>
   * Is publishing allowed?
   * </pre>
   *
   * <code>bool can_publish = 3;</code>
   * @return The canPublish.
   */
  boolean getCanPublish();

  /**
   * <pre>
   * Is subscription allowed?
   * </pre>
   *
   * <code>bool can_subscribe = 4;</code>
   * @return The canSubscribe.
   */
  boolean getCanSubscribe();

  /**
   * <pre>
   * ID of the current topic schema, which can be used for
   * publishing of generically serialized events.
   * </pre>
   *
   * <code>string schema_id = 5;</code>
   * @return The schemaId.
   */
  java.lang.String getSchemaId();
  /**
   * <pre>
   * ID of the current topic schema, which can be used for
   * publishing of generically serialized events.
   * </pre>
   *
   * <code>string schema_id = 5;</code>
   * @return The bytes for schemaId.
   */
  com.google.protobuf.ByteString
      getSchemaIdBytes();

  /**
   * <pre>
   * RPC ID used to trace errors.
   * </pre>
   *
   * <code>string rpc_id = 6;</code>
   * @return The rpcId.
   */
  java.lang.String getRpcId();
  /**
   * <pre>
   * RPC ID used to trace errors.
   * </pre>
   *
   * <code>string rpc_id = 6;</code>
   * @return The bytes for rpcId.
   */
  com.google.protobuf.ByteString
      getRpcIdBytes();
}
